---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance-1
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-ubuntu2004}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    networks:
      - name: ${MOLECULE_DISTRO:-ubuntu2004}-${CI_PROJECT_NAME:-default}
    privileged: true
    pre_build_image: true
    groups:
      - glusterfs
  - name: instance-2
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-ubuntu2004}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    networks:
      - name: ${MOLECULE_DISTRO:-ubuntu2004}-${CI_PROJECT_NAME:-default}
    privileged: true
    pre_build_image: true
    groups:
      - glusterfs
  - name: instance-3
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-ubuntu2004}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    networks:
      - name: ${MOLECULE_DISTRO:-ubuntu2004}-${CI_PROJECT_NAME:-default}
    privileged: true
    pre_build_image: true
    groups:
      - glusterfs
provisioner:
  name: ansible
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
  inventory:
    group_vars:
      all:
        glusterfs_version: 8
        glusterfs_server_group: glusterfs
        glusterfs_bricks_dir: /data
        glusterfs_config: true
    host_vars:
      instance-1:
      instance-2:
      isntance-3:
scenario:
  name: cluster
verifier:
  name: testinfra
  lint:
    name: flake8             
